# Generated by Django 2.2.5 on 2019-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_email',
            field=models.CharField(default='test@mail.ru', max_length=100),
            preserve_default=False,
        ),
    ]
